import pyautogui
import time

pyautogui.moveTo(1034,1061,3)
pyautogui.click()
time.sleep(2)


pyautogui.moveTo(824,68,3)
pyautogui.click()
pyautogui.write('https://mail.google.com/mail/u/0/?tab=um#inbox',0.1 )
pyautogui.press('Enter')
time.sleep(4)


pyautogui.moveTo(127,241,1)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(1237,462,1)
pyautogui.click()
time.sleep(1)
pyautogui.write('devpatriciaribeiro@gmail.com', 0.1)
time.sleep(2)
pyautogui.moveTo(1467,727,1)
pyautogui.click()
pyautogui.write('Mussum Ipsum, cacilds vidis litro abertis. Delegadis gente finis, bibendum egestas augue arcu ut est. Interagi no mé, cursus quis, vehicula ac nisi.', 0.1)
time.sleep(1)
pyautogui.moveTo(1255,503,1)
pyautogui.click()
pyautogui.write('Relatório do dia', 0.1)
pyautogui.moveTo(1371,970,1)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(1097,912,1)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(87,274,1)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(291,226,1)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(651,556,1)
pyautogui.click()
time.sleep(4)
pyautogui.moveTo(1225,983,1)
pyautogui.click()
time.sleep(1)

